
services:
  #web
  web:
    image: nginx:latest
    container_name: lara-task-web
    ports:
      - "8888:80"
    volumes:
      - ./src:/var/www/html:delegated
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - db
    networks:
      - lara-network
  #app
  app:
    container_name: lara-task-app
    build:
      context: ./php
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - lara-network
  #db
  db:
    container_name: lara-task-db
    image: mysql:8
    ports:
      - "3308:3306"
    env_file:
      - ./env/mysql.env
    networks:
      - lara-network
  #composer
  composer:
    build:
      context: ./php
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - lara-network
  #artisan
  artisan:
    build:
      context: ./php
      dockerfile: php.dockerfile
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html:delegated
    entrypoint: ["php","artisan"]
    networks:
      - lara-network
  #npm
  npm:
    image: node:latest
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes: 
        - ./src:/var/www/html:delegated
    networks:
      - lara-network

  #vite
  vite:
    image: node:latest
    working_dir: /var/www/html
    volumes:
      - ./src/:/var/www/html
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    ports:
      - "5173:5173"
    networks:
      - lara-network

networks:
  lara-network:
    driver: bridge

